#!/usr/bin/env python3
"""Investigate actual Z3 formulas generated by model checker.

This script runs a countermodel example with both finitary and native
quantifiers, printing the actual Z3 formulas to understand the difference.
"""

import os
import sys

# Ensure local src is prioritized
src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src'))
sys.path.insert(0, src_path)

from types import SimpleNamespace
from unittest.mock import Mock

import z3


def run_example_with_mode(mode: str, example_name: str = "CF_CM_1"):
    """Run a countermodel example with specified quantifier mode."""

    # Configure mode
    from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
    from model_checker.solver.lifecycle import invalidate_all_caches
    from model_checker.utils.z3_helpers import set_quantifier_mode, get_quantifier_mode
    from model_checker import z3_shim
    from model_checker.syntactic.atoms import reset_atom_sort

    # Full cache invalidation
    clear_cli_backend()
    reset_registry()
    z3_shim._reset_backend()
    reset_atom_sort()
    invalidate_all_caches()

    # Set mode
    if mode == "finitary":
        set_cli_backend("z3")
        set_quantifier_mode("finitary")
    elif mode == "native":
        set_cli_backend("z3")
        set_quantifier_mode("native")
    else:
        raise ValueError(f"Unknown mode: {mode}")

    print(f"\n{'='*70}")
    print(f"Running {example_name} with {mode} quantifiers")
    print(f"{'='*70}")

    # Get theory and examples
    from model_checker.theory_lib.logos import get_theory
    from model_checker.theory_lib.logos.examples import all_subtheory_examples

    subtheories = ["extensional", "modal", "counterfactual"]
    theory = get_theory(subtheories)

    cf_examples = all_subtheory_examples.get("counterfactual", {})
    if example_name not in cf_examples:
        print(f"Example {example_name} not found!")
        return None

    example_case = cf_examples[example_name]
    premises, conclusions, settings = example_case

    print(f"\nExample: {example_name}")
    print(f"Premises: {premises}")
    print(f"Conclusions: {conclusions}")
    print(f"Settings N: {settings.get('N', 2)}")

    # Create mock module for the example
    from model_checker.builder.example import BuildExample

    mock_module = Mock()
    mock_module.semantic_theories = {"logos": theory}

    general_settings = {
        "N": settings.get("N", 2),
        "contingent": settings.get("contingent", False),
        "disjoint": settings.get("disjoint", False),
        "non_empty": settings.get("non_empty", True),
        "non_null": settings.get("non_null", True),
        "print_constraints": True,  # Enable to see formulas
        "save_output": False,
        "print_impossible": False,
        "print_z3": True,  # Enable to see Z3 output
        "max_time": settings.get("max_time", 5),
    }
    mock_module.general_settings = general_settings
    mock_module.raw_general_settings = general_settings
    mock_module.module_flags = SimpleNamespace(
        contingent=settings.get("contingent", False),
        disjoint=settings.get("disjoint", False),
        non_empty=settings.get("non_empty", False),
        non_null=settings.get("non_null", False),
        print_constraints=True,
        save_output=False,
        print_impossible=False,
        print_z3=True,
        maximize=False,
    )

    # Build the example
    try:
        example = BuildExample(mock_module, theory, example_case)
        if example.model_structure.z3_model_status:
            result = "sat"
            print(f"\nResult: SAT (countermodel found)")
        else:
            result = "unsat"
            print(f"\nResult: UNSAT (no countermodel)")
        return result
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        return None


def extract_quantifier_formulas():
    """Extract and compare the quantifier formulas for both modes."""

    print("\n" + "=" * 70)
    print("EXTRACTING QUANTIFIER FORMULA STRUCTURE")
    print("=" * 70)

    # Configure for Z3 backend
    from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
    from model_checker.solver.lifecycle import invalidate_all_caches
    from model_checker.utils.z3_helpers import set_quantifier_mode
    from model_checker import z3_shim
    from model_checker.syntactic.atoms import reset_atom_sort

    # Full reset
    clear_cli_backend()
    reset_registry()
    z3_shim._reset_backend()
    reset_atom_sort()
    invalidate_all_caches()

    set_cli_backend("z3")
    set_quantifier_mode("native")  # Start with native to see the structure

    from model_checker.theory_lib.logos import get_theory

    # Get minimal theory
    subtheories = ["extensional", "modal", "counterfactual"]
    theory = get_theory(subtheories)

    # Access semantics directly
    semantics = theory["semantics"]
    N = 2  # Use small N for inspection

    print(f"\nN = {N}")
    print(f"Semantics class: {type(semantics).__name__}")

    # Look at the maximal function (uses ForAll)
    from model_checker.utils.z3_helpers import ForAll, Exists, _finitary_forall, _native_forall

    x = z3.BitVec("x", N)
    w = z3.BitVec("w", N)

    # Simulate what maximal(w) looks like
    # maximal(w) = ForAll x: compatible(x, w) => is_part_of(x, w)

    compatible = z3.Function("compatible", z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())
    is_part_of = z3.Function("is_part_of", z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())

    formula_body = z3.Implies(compatible(x, w), is_part_of(x, w))

    print("\n" + "-" * 70)
    print("maximal(w) = ForAll x: compatible(x,w) => is_part_of(x,w)")
    print("-" * 70)

    # Native version
    native_maximal = _native_forall([x], formula_body)
    print(f"\nNative ForAll:")
    print(f"  {native_maximal}")

    # Finitary version
    set_quantifier_mode("finitary")
    finitary_maximal = _finitary_forall([x], formula_body)
    print(f"\nFinitary ForAll (N=2, so 4 terms):")
    print(f"  {z3.simplify(finitary_maximal)}")

    # Now look at the counterfactual formula
    print("\n" + "-" * 70)
    print("Counterfactual: ForAll [x,u]: (verify(x) & is_alt(u,x,w)) => true_B(u)")
    print("-" * 70)

    u = z3.BitVec("u", N)
    verify = z3.Function("verify", z3.BitVecSort(N), z3.BoolSort())
    is_alt = z3.Function("is_alt", z3.BitVecSort(N), z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())
    true_B = z3.Function("true_B", z3.BitVecSort(N), z3.BoolSort())

    cf_body = z3.Implies(
        z3.And(verify(x), is_alt(u, x, w)),
        true_B(u)
    )

    # Native version
    set_quantifier_mode("native")
    native_cf = _native_forall([x, u], cf_body)
    print(f"\nNative ForAll:")
    print(f"  {native_cf}")

    # Finitary version
    set_quantifier_mode("finitary")
    finitary_cf = _finitary_forall([x, u], cf_body)
    print(f"\nFinitary ForAll (N=2, so 16 terms for [x,u]):")
    simplified = z3.simplify(finitary_cf)
    print(f"  {simplified}")

    print("\n" + "-" * 70)
    print("KEY OBSERVATION")
    print("-" * 70)
    print("""
The finitary version expands to 2^N conjuncts for each quantified variable.
For ForAll([x,u], body) with N=2:
  - Finitary: 4*4 = 16 conjuncts: And(body[0,0], body[0,1], ..., body[3,3])
  - Native: z3.ForAll([x,u], body)

The semantic meaning should be identical for finite domains.
The difference lies in HOW Z3 handles the quantifier:
  - Finitary: Pure bitvector problem, no quantifiers
  - Native: Quantified formula requires instantiation/elimination
""")


def test_solver_strategies():
    """Test different Z3 solver strategies with quantified bitvector formulas."""

    print("\n" + "=" * 70)
    print("TESTING Z3 SOLVER STRATEGIES")
    print("=" * 70)

    N = 2

    # Create a problem known to be SAT but with quantifiers
    possible = z3.Function("possible", z3.BitVecSort(N), z3.BoolSort())
    verify = z3.Function("verify", z3.BitVecSort(N), z3.BoolSort())
    true_at = z3.Function("true_at", z3.BitVecSort(N), z3.BoolSort())
    is_alt = z3.Function("is_alt", z3.BitVecSort(N), z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())

    x = z3.BitVec("x", N)
    u = z3.BitVec("u", N)
    w = z3.BitVec("w", N)

    # Setup: Simple model with w=0, one verifier at state 1, one alternative at 1
    base_constraints = z3.And(
        # Main world is 0
        w == z3.BitVecVal(0, N),
        # States 0,1 are possible
        possible(z3.BitVecVal(0, N)),
        possible(z3.BitVecVal(1, N)),
        z3.Not(possible(z3.BitVecVal(2, N))),
        z3.Not(possible(z3.BitVecVal(3, N))),
        # Antecedent A verified by state 1
        verify(z3.BitVecVal(1, N)),
        z3.Not(verify(z3.BitVecVal(0, N))),
        z3.Not(verify(z3.BitVecVal(2, N))),
        z3.Not(verify(z3.BitVecVal(3, N))),
        # World 1 is alternative via state 1 from world 0
        is_alt(z3.BitVecVal(1, N), z3.BitVecVal(1, N), z3.BitVecVal(0, N)),
        # B is FALSE at alternative world 1 (this makes A boxright B false)
        z3.Not(true_at(z3.BitVecVal(1, N))),
    )

    # The counterfactual truth condition: ForAll x,u: (verify(x) & is_alt(u,x,w)) => true_at(u)
    cf_formula = z3.ForAll([x, u], z3.Implies(
        z3.And(verify(x), is_alt(u, x, w)),
        true_at(u)
    ))

    print("\nScenario: Find model where A boxright B is TRUE")
    print("  This should be UNSAT because we've set up B false at the alternative")
    print()

    # Test 1: Default solver
    print("-" * 70)
    print("Test 1: Default solver")
    print("-" * 70)
    s1 = z3.Solver()
    s1.add(base_constraints)
    s1.add(cf_formula)
    result1 = s1.check()
    print(f"  Result: {result1}")
    print()

    # Test 2: With MBQI
    print("-" * 70)
    print("Test 2: With MBQI (model-based quantifier instantiation)")
    print("-" * 70)
    s2 = z3.Solver()
    s2.set("smt.mbqi", True)
    s2.add(base_constraints)
    s2.add(cf_formula)
    result2 = s2.check()
    print(f"  Result: {result2}")
    print()

    # Test 3: With finite sorts hint
    print("-" * 70)
    print("Test 3: Using finite model finding")
    print("-" * 70)
    s3 = z3.Solver()
    s3.set("smt.mbqi", True)
    s3.set("smt.mbqi.max_iterations", 100)
    s3.add(base_constraints)
    s3.add(cf_formula)
    result3 = s3.check()
    print(f"  Result: {result3}")
    print()

    # Test 4: Finitary (ground formula, no quantifiers)
    print("-" * 70)
    print("Test 4: Finitary (ground formula)")
    print("-" * 70)
    cf_finitary = z3.And([
        z3.Implies(
            z3.And(verify(z3.BitVecVal(i, N)), is_alt(z3.BitVecVal(j, N), z3.BitVecVal(i, N), w)),
            true_at(z3.BitVecVal(j, N))
        )
        for i in range(4) for j in range(4)
    ])
    s4 = z3.Solver()
    s4.add(base_constraints)
    s4.add(cf_finitary)
    result4 = s4.check()
    print(f"  Result: {result4}")
    print()

    # Now test the opposite: Find model where A boxright B is FALSE (i.e., Exists witness)
    print("=" * 70)
    print("INVERSE: Find model where A boxright B is FALSE (countermodel)")
    print("=" * 70)

    # Remove the true_at(1)=false constraint, let solver find it
    base_constraints_open = z3.And(
        w == z3.BitVecVal(0, N),
        possible(z3.BitVecVal(0, N)),
        possible(z3.BitVecVal(1, N)),
        z3.Not(possible(z3.BitVecVal(2, N))),
        z3.Not(possible(z3.BitVecVal(3, N))),
        verify(z3.BitVecVal(1, N)),
        z3.Not(verify(z3.BitVecVal(0, N))),
        z3.Not(verify(z3.BitVecVal(2, N))),
        z3.Not(verify(z3.BitVecVal(3, N))),
        is_alt(z3.BitVecVal(1, N), z3.BitVecVal(1, N), z3.BitVecVal(0, N)),
    )

    # The premise: A boxright C is TRUE
    # Conclusion: (A & B) boxright C is TRUE
    # Countermodel: Premises true, conclusion false

    # For simplicity, just test: Can we find assignment where cf_formula is TRUE?

    print("-" * 70)
    print("Can native quantifier find satisfying model?")
    print("-" * 70)

    s5 = z3.Solver()
    s5.add(base_constraints_open)
    s5.add(cf_formula)
    result5 = s5.check()
    print(f"  Native ForAll: {result5}")

    if result5 == z3.sat:
        m = s5.model()
        print(f"  true_at(0) = {m.evaluate(true_at(z3.BitVecVal(0, N)))}")
        print(f"  true_at(1) = {m.evaluate(true_at(z3.BitVecVal(1, N)))}")

    s6 = z3.Solver()
    s6.add(base_constraints_open)
    s6.add(cf_finitary)
    result6 = s6.check()
    print(f"  Finitary And: {result6}")

    if result6 == z3.sat:
        m = s6.model()
        print(f"  true_at(0) = {m.evaluate(true_at(z3.BitVecVal(0, N)))}")
        print(f"  true_at(1) = {m.evaluate(true_at(z3.BitVecVal(1, N)))}")

    print()
    print("=" * 70)
    print("ANALYSIS")
    print("=" * 70)
    print("""
If both native and finitary return the same result, the issue is elsewhere.
If they differ, we've isolated the quantifier handling difference.
""")


def main():
    # First extract and examine formula structures
    extract_quantifier_formulas()

    # Test solver strategies
    test_solver_strategies()

    print("\n" + "=" * 70)
    print("RUNNING ACTUAL MODEL CHECKER EXAMPLE")
    print("=" * 70)

    # Run with finitary
    result_fin = run_example_with_mode("finitary", "CF_CM_18")  # Must Factivity - simpler

    # Run with native
    result_nat = run_example_with_mode("native", "CF_CM_18")

    print("\n" + "=" * 70)
    print("COMPARISON")
    print("=" * 70)
    print(f"Finitary result: {result_fin}")
    print(f"Native result:   {result_nat}")

    if result_fin == "sat" and result_nat == "unsat":
        print("\nCONFIRMED: Native quantifiers return UNSAT for SAT problem!")
    elif result_fin == result_nat:
        print("\nBoth modes agree on this example.")


if __name__ == "__main__":
    main()
