#!/usr/bin/env python3
"""Directly examine the formulas generated by the counterfactual operator.

This script creates the counterfactual formula exactly as the operator does,
to understand what's different between finitary and native modes.
"""

import os
import sys

# Ensure local src is prioritized
src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src'))
sys.path.insert(0, src_path)

import z3


def test_counterfactual_formula_directly():
    """Build the counterfactual formula exactly as the operator does."""

    print("=" * 70)
    print("DIRECT COUNTERFACTUAL FORMULA ANALYSIS")
    print("=" * 70)

    for mode in ["finitary", "native"]:
        print(f"\n{'='*70}")
        print(f"MODE: {mode.upper()}")
        print(f"{'='*70}")

        # Reset everything
        from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
        from model_checker.solver.lifecycle import invalidate_all_caches
        from model_checker.utils.z3_helpers import set_quantifier_mode
        from model_checker import z3_shim
        from model_checker.syntactic.atoms import reset_atom_sort

        clear_cli_backend()
        reset_registry()
        z3_shim._reset_backend()
        reset_atom_sort()
        invalidate_all_caches()

        set_cli_backend("z3")
        set_quantifier_mode(mode)

        # Now import the mode-aware ForAll/Exists
        from model_checker.utils import ForAll, Exists

        N = 2

        # Create semantics-like functions
        # These are the actual Z3 functions as created by LogosSemantics

        # Uninterpreted functions for the model
        verify = z3.Function("verify", z3.BitVecSort(N), z3.BoolSort())
        falsify = z3.Function("falsify", z3.BitVecSort(N), z3.BoolSort())
        possible = z3.Function("possible", z3.BitVecSort(N), z3.BoolSort())

        # Part-of is just bitvector AND relation: x is part of y iff x & y == x
        def is_part_of(x, y):
            return (x & y) == x

        # Fusion is bitvector OR
        def fusion(x, y):
            return x | y

        # Compatible: fusion is possible
        def compatible(x, y):
            return possible(fusion(x, y))

        # Maximal: ForAll max_x: compatible(max_x, w) => is_part_of(max_x, w)
        def maximal(w):
            max_x = z3.BitVec("max_x", N)
            return ForAll(
                max_x,
                z3.Implies(compatible(max_x, w), is_part_of(max_x, w))
            )

        # Is world: possible and maximal
        def is_world(w):
            return z3.And(possible(w), maximal(w))

        # Max compatible part: z is maximal part of w compatible with y
        def max_compatible_part(z_s, w_s, y_s):
            mcp_x = z3.BitVec("mcp_x", N)
            return z3.And(
                is_part_of(z_s, w_s),
                compatible(z_s, y_s),
                ForAll(
                    mcp_x,
                    z3.Implies(
                        z3.And(
                            is_part_of(mcp_x, w_s),
                            compatible(mcp_x, y_s),
                            is_part_of(z_s, mcp_x)
                        ),
                        z_s == mcp_x
                    )
                )
            )

        # Is alternative: u is y-alternative to w
        def is_alternative(u, y, w):
            alt_z = z3.BitVec("alt_z", N)
            return z3.And(
                is_world(u),
                is_part_of(y, u),
                Exists(
                    alt_z,
                    z3.And(
                        is_part_of(alt_z, u),
                        max_compatible_part(alt_z, w, y)
                    )
                )
            )

        # Extended verify for atomic sentence A
        def extended_verify_A(y, w):
            """y verifies A at evaluation point with world w"""
            # For atomic: y verifies A and y is part of w
            return z3.And(verify(y), is_part_of(y, w))

        # Now build the counterfactual false_at formula
        # (A boxright B) is false at world w iff:
        # Exists x, u: extended_verify(x, A, {world: w})
        #              & is_alternative(u, x, w)
        #              & false_at(B, {world: u})

        # For atomic B, false_at is: exists z: falsify(z) & is_part_of(z, u)
        def false_at_B(u):
            fz = z3.BitVec("f_z", N)
            return Exists(
                fz,
                z3.And(falsify(fz), is_part_of(fz, u))
            )

        # Main world
        main_w = z3.BitVec("w", N)
        cf_x = z3.BitVec("f_cf_x", N)  # Variable names as in the actual operator
        cf_u = z3.BitVec("f_cf_u", N)

        # The counterfactual false_at formula
        cf_false = Exists(
            [cf_x, cf_u],
            z3.And(
                extended_verify_A(cf_x, {"world": main_w}["world"]),
                is_alternative(cf_u, cf_x, main_w),
                false_at_B(cf_u)
            )
        )

        print(f"\nCounterfactual false_at formula:")
        print(f"  Type: {type(cf_false)}")
        print(f"  Is quantifier: {z3.is_quantifier(cf_false) if hasattr(cf_false, 'decl') else 'N/A (And)'}")

        # Print formula structure
        if mode == "finitary":
            # Finitary produces a big Or of ground terms
            print(f"\nFinitary expansion produces Or/And of ground terms:")
            print(f"  Simplified: {z3.simplify(cf_false)}")
        else:
            print(f"\nNative Exists produces quantified formula:")
            print(f"  {cf_false}")

        # Now test satisfiability
        # Setup: We want to find a model where A and B are true at w,
        # but A boxright B is false

        # Frame constraint: possibility downward closure
        frame_x, frame_y = z3.BitVecs("frame_x frame_y", N)
        possibility_closure = ForAll(
            [frame_x, frame_y],
            z3.Implies(
                z3.And(possible(frame_y), is_part_of(frame_x, frame_y)),
                possible(frame_x)
            )
        )

        # Main world is a world
        main_world_constraint = is_world(main_w)

        # Premise: A is true at w (there exists a verifier for A in w)
        px = z3.BitVec("p_x", N)
        premise_A = Exists(
            px,
            z3.And(verify(px), is_part_of(px, main_w))
        )

        # Premise: B is true at w (there exists a verifier for B in w - use not falsify for simplicity)
        # Actually for simplicity: B true means no falsifier in w
        # But let's make it: there exists a state that verifies B (non-falsifier)
        # Simpler: just assume B is not false (no falsifier part of w)
        # premise_B = For all z in w: not falsify(z)
        pb = z3.BitVec("p_b", N)
        premise_B = ForAll(
            pb,
            z3.Implies(is_part_of(pb, main_w), z3.Not(falsify(pb)))
        )

        # Conclusion (negated for countermodel search): A boxright B is FALSE
        conclusion_false = cf_false

        # Combine all constraints
        s = z3.Solver()
        s.set("timeout", 30000)  # 30s

        s.add(possibility_closure)
        s.add(main_world_constraint)
        s.add(premise_A)
        s.add(premise_B)
        s.add(conclusion_false)

        print(f"\n--- Solving for countermodel ---")
        result = s.check()
        print(f"Result: {result}")

        if result == z3.sat:
            print("FOUND COUNTERMODEL!")
            m = s.model()
            # Try to extract some values
            for i in range(4):
                bv = z3.BitVecVal(i, N)
                print(f"  possible({i}) = {m.evaluate(possible(bv))}")
                print(f"  verify({i}) = {m.evaluate(verify(bv))}")
                print(f"  falsify({i}) = {m.evaluate(falsify(bv))}")
        elif result == z3.unsat:
            print("NO COUNTERMODEL - Problem is UNSAT")
        else:
            print("UNKNOWN/TIMEOUT")


def count_quantifiers(formula):
    """Count quantifiers in a formula."""
    count = 0
    stack = [formula]
    seen = set()

    while stack:
        f = stack.pop()
        if id(f) in seen:
            continue
        seen.add(id(f))

        if z3.is_quantifier(f):
            count += 1

        if hasattr(f, 'children'):
            for child in f.children():
                stack.append(child)

    return count


def analyze_formula_structure():
    """Analyze the structure of the formulas produced by each mode."""

    print("\n" + "=" * 70)
    print("FORMULA STRUCTURE ANALYSIS")
    print("=" * 70)

    for mode in ["finitary", "native"]:
        # Reset
        from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
        from model_checker.solver.lifecycle import invalidate_all_caches
        from model_checker.utils.z3_helpers import set_quantifier_mode
        from model_checker import z3_shim
        from model_checker.syntactic.atoms import reset_atom_sort

        clear_cli_backend()
        reset_registry()
        z3_shim._reset_backend()
        reset_atom_sort()
        invalidate_all_caches()

        set_cli_backend("z3")
        set_quantifier_mode(mode)

        from model_checker.utils import ForAll, Exists

        N = 2
        x = z3.BitVec("x", N)

        # Simple ForAll
        P = z3.Function("P", z3.BitVecSort(N), z3.BoolSort())
        simple_forall = ForAll(x, P(x))

        # Nested ForAll-Exists
        Q = z3.Function("Q", z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())
        y = z3.BitVec("y", N)
        nested = ForAll(x, Exists(y, Q(x, y)))

        print(f"\n--- {mode.upper()} ---")
        print(f"Simple ForAll x: P(x):")
        print(f"  {simple_forall}")
        print(f"  Quantifier count: {count_quantifiers(simple_forall)}")

        print(f"\nNested ForAll x: Exists y: Q(x,y):")
        print(f"  {nested}")
        print(f"  Quantifier count: {count_quantifiers(nested)}")


def main():
    # First do structure analysis
    analyze_formula_structure()

    # Then test the full counterfactual formula
    test_counterfactual_formula_directly()


if __name__ == "__main__":
    main()
