#!/usr/bin/env python3
"""Trace exactly what formulas the model checker generates.

This script runs through the model checker's constraint generation
to capture the exact Z3 formulas for comparison.
"""

import os
import sys

# Ensure local src is prioritized
src_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src'))
sys.path.insert(0, src_path)

import z3


def capture_constraints(mode: str, example_name: str = "CF_CM_18"):
    """Capture the constraints generated by the model checker."""

    # Configure mode
    from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
    from model_checker.solver.lifecycle import invalidate_all_caches
    from model_checker.utils.z3_helpers import set_quantifier_mode, get_quantifier_mode
    from model_checker import z3_shim
    from model_checker.syntactic.atoms import reset_atom_sort

    # Full cache invalidation
    clear_cli_backend()
    reset_registry()
    z3_shim._reset_backend()
    reset_atom_sort()
    invalidate_all_caches()

    # Set mode
    if mode == "finitary":
        set_cli_backend("z3")
        set_quantifier_mode("finitary")
    elif mode == "native":
        set_cli_backend("z3")
        set_quantifier_mode("native")
    else:
        raise ValueError(f"Unknown mode: {mode}")

    print(f"\n{'='*70}")
    print(f"Capturing constraints for {example_name} with {mode} quantifiers")
    print(f"{'='*70}")

    # Get theory and examples
    from model_checker.theory_lib.logos import get_theory
    from model_checker.theory_lib.logos.examples import all_subtheory_examples

    subtheories = ["extensional", "modal", "counterfactual"]
    theory = get_theory(subtheories)

    cf_examples = all_subtheory_examples.get("counterfactual", {})
    if example_name not in cf_examples:
        print(f"Example {example_name} not found!")
        return None

    example_case = cf_examples[example_name]
    premises, conclusions, settings = example_case

    print(f"\nExample: {example_name}")
    print(f"Premises: {premises}")
    print(f"Conclusions: {conclusions}")

    # Use N=2 for simpler formulas
    N = 2

    # Build the model constraints manually to capture them
    from model_checker.models.syntax import ModelSyntax
    from model_checker.models.model_constraints import ModelConstraints
    from model_checker.solver import create_solver

    # Initialize semantics with N=2
    semantics = theory["semantics"]
    semantics_instance = semantics(N)

    # Create syntax from premises/conclusions
    syntax = ModelSyntax(
        premises=premises,
        conclusions=conclusions,
        operators=semantics_instance.operator_registry,
        quantified=False,
        logic="propositional"
    )

    # Create model constraints
    model_constraints = ModelConstraints(
        syntax=syntax,
        semantics=semantics_instance,
        proposition_class=theory["proposition_class"],
        settings={"N": N},
    )

    print(f"\n--- Frame Constraints ({len(model_constraints.frame_constraints)}) ---")
    for i, c in enumerate(model_constraints.frame_constraints):
        print(f"  [{i}] {c}")

    print(f"\n--- Model Constraints ({len(model_constraints.model_constraints)}) ---")
    for i, c in enumerate(model_constraints.model_constraints[:10]):  # First 10
        print(f"  [{i}] {c}")
    if len(model_constraints.model_constraints) > 10:
        print(f"  ... and {len(model_constraints.model_constraints) - 10} more")

    print(f"\n--- Premise Constraints ({len(model_constraints.premise_constraints)}) ---")
    for i, c in enumerate(model_constraints.premise_constraints):
        print(f"  [{i}] {c}")

    print(f"\n--- Conclusion Constraints ({len(model_constraints.conclusion_constraints)}) ---")
    for i, c in enumerate(model_constraints.conclusion_constraints):
        print(f"  [{i}] {c}")

    # Now solve and see result
    solver = create_solver({"N": N, "max_time": 5})
    for c in model_constraints.frame_constraints:
        solver.add(c)
    for c in model_constraints.model_constraints:
        solver.add(c)
    for c in model_constraints.premise_constraints:
        solver.add(c)
    for c in model_constraints.conclusion_constraints:
        solver.add(c)

    result = solver.check()
    print(f"\n--- Result: {result} ---")

    return model_constraints


def compare_conclusion_formulas():
    """Compare the actual conclusion formulas for finitary vs native."""

    print("\n" + "=" * 70)
    print("COMPARING CONCLUSION FORMULA STRUCTURE")
    print("=" * 70)

    from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
    from model_checker.solver.lifecycle import invalidate_all_caches
    from model_checker.utils.z3_helpers import set_quantifier_mode
    from model_checker import z3_shim
    from model_checker.syntactic.atoms import reset_atom_sort

    # Test both modes
    for mode in ["finitary", "native"]:
        # Full reset
        clear_cli_backend()
        reset_registry()
        z3_shim._reset_backend()
        reset_atom_sort()
        invalidate_all_caches()

        set_cli_backend("z3")
        set_quantifier_mode(mode)

        from model_checker.theory_lib.logos import get_theory

        subtheories = ["extensional", "modal", "counterfactual"]
        theory = get_theory(subtheories)
        semantics = theory["semantics"]

        N = 2
        sem_instance = semantics({"N": N})

        # Parse a simple counterfactual: A boxright B
        from model_checker.syntactic import Sentence

        sentence = Sentence("(A \\boxright B)", sem_instance.operator_registry)

        # Get the false_at condition (this is what gets added to conclusions)
        main_world = z3.BitVec("test_w", N)
        eval_point = {"world": main_world}

        false_cond = sem_instance.false_at(sentence, eval_point)

        print(f"\n--- {mode.upper()} MODE ---")
        print(f"false_at(A boxright B, {{world: w}}):")
        print(f"  {false_cond}")

        # Check if it contains quantifiers
        has_quantifier = z3.is_quantifier(false_cond)
        print(f"  Is quantifier: {has_quantifier}")

        # Try to simplify
        simplified = z3.simplify(false_cond)
        print(f"  Simplified: {simplified}")


def test_minimal_counterfactual():
    """Test minimal counterfactual scenario directly."""

    print("\n" + "=" * 70)
    print("MINIMAL COUNTERFACTUAL TEST")
    print("=" * 70)

    from model_checker.solver.registry import set_cli_backend, clear_cli_backend, reset_registry
    from model_checker.solver.lifecycle import invalidate_all_caches
    from model_checker.utils.z3_helpers import set_quantifier_mode, ForAll, Exists
    from model_checker import z3_shim
    from model_checker.syntactic.atoms import reset_atom_sort

    for mode in ["finitary", "native"]:
        print(f"\n--- Testing {mode.upper()} mode ---")

        # Full reset
        clear_cli_backend()
        reset_registry()
        z3_shim._reset_backend()
        reset_atom_sort()
        invalidate_all_caches()

        set_cli_backend("z3")
        set_quantifier_mode(mode)

        # Reimport to get mode-aware ForAll
        from model_checker.utils.z3_helpers import ForAll as MC_ForAll, Exists as MC_Exists

        N = 2

        # Create functions similar to semantics
        verify = z3.Function("verify", z3.BitVecSort(N), z3.BoolSort())
        possible = z3.Function("possible", z3.BitVecSort(N), z3.BoolSort())
        part_of = z3.Function("part_of", z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())
        true_at = z3.Function("true_at", z3.BitVecSort(N), z3.BoolSort())
        compatible = z3.Function("compatible", z3.BitVecSort(N), z3.BitVecSort(N), z3.BoolSort())

        x = z3.BitVec("x", N)
        u = z3.BitVec("u", N)
        w = z3.BitVec("main_w", N)

        # Define is_alternative using mode-aware Exists
        z_var = z3.BitVec("alt_z", N)

        def is_part_of(a, b):
            return part_of(a, b)

        def is_fusion(a, b):
            return a | b

        def is_possible(s):
            return possible(s)

        def is_compatible(a, b):
            return is_possible(is_fusion(a, b))

        # maximal using MC_ForAll (mode-aware)
        def maximal(state):
            mx = z3.BitVec("max_x", N)
            return MC_ForAll(
                mx,
                z3.Implies(is_compatible(mx, state), is_part_of(mx, state))
            )

        def is_world(state):
            return z3.And(is_possible(state), maximal(state))

        def max_compatible_part(z_s, w_s, y_s):
            """z is a maximal part of w compatible with y"""
            mx2 = z3.BitVec("mcp_x", N)
            return z3.And(
                is_part_of(z_s, w_s),
                is_compatible(z_s, y_s),
                MC_ForAll(
                    mx2,
                    z3.Implies(
                        z3.And(
                            is_part_of(mx2, w_s),
                            is_compatible(mx2, y_s),
                            is_part_of(z_s, mx2)
                        ),
                        z_s == mx2
                    )
                )
            )

        def is_alternative(u_s, y_s, w_s):
            """u is y-alternative to w"""
            zz = z3.BitVec("alt_zz", N)
            return z3.And(
                is_world(u_s),
                is_part_of(y_s, u_s),
                MC_Exists(
                    zz,
                    z3.And(
                        is_part_of(zz, u_s),
                        max_compatible_part(zz, w_s, y_s)
                    )
                )
            )

        # Extended verify (simplified)
        def extended_verify(y_s, w_s):
            """y verifies A at w - simplified for atomic A"""
            return z3.And(verify(y_s), is_part_of(y_s, w_s))

        # Counterfactual false_at (A boxright B is false at w)
        # Exists x,u: extended_verify(x,w) & is_alternative(u,x,w) & NOT true_at(u)
        cf_false = MC_Exists(
            [x, u],
            z3.And(
                extended_verify(x, w),
                is_alternative(u, x, w),
                z3.Not(true_at(u))
            )
        )

        print(f"Counterfactual false_at formula:")
        print(f"  {cf_false}")

        # Basic model setup
        base = z3.And(
            # Main world is 0
            w == z3.BitVecVal(0, N),
            # Possible states
            possible(z3.BitVecVal(0, N)),
            possible(z3.BitVecVal(1, N)),
            z3.Not(possible(z3.BitVecVal(2, N))),
            z3.Not(possible(z3.BitVecVal(3, N))),
            # Part relation (reflexive)
            part_of(z3.BitVecVal(0, N), z3.BitVecVal(0, N)),
            part_of(z3.BitVecVal(1, N), z3.BitVecVal(1, N)),
            part_of(z3.BitVecVal(2, N), z3.BitVecVal(2, N)),
            part_of(z3.BitVecVal(3, N), z3.BitVecVal(3, N)),
            # Compatible with fusion being possible
            # (simplification: fusion = OR, possible defined above)
        )

        # Test: Can we find a countermodel to A boxright B?
        # Need: Premises (A true, B true), Conclusion false (A boxright B false)

        # Premise: A is true at w (there's a verifier for A in w)
        premise_A = z3.Or([
            z3.And(verify(z3.BitVecVal(i, N)), is_part_of(z3.BitVecVal(i, N), w))
            for i in range(4)
        ])

        # Premise: B is true at w
        premise_B = true_at(w)

        # Conclusion: A boxright B is false at w
        conclusion_cf_false = cf_false

        s = z3.Solver()
        s.set("timeout", 10000)  # 10s timeout
        s.add(base)
        s.add(premise_A)
        s.add(premise_B)
        s.add(conclusion_cf_false)

        result = s.check()
        print(f"\nResult (looking for countermodel): {result}")

        if result == z3.sat:
            m = s.model()
            print("Found countermodel!")
        elif result == z3.unsat:
            print("No countermodel found (problem is UNSAT)")
        else:
            print(f"Unknown/timeout: {result}")


def main():
    print("=" * 70)
    print("TRACING MODEL CHECKER CONSTRAINT GENERATION")
    print("=" * 70)

    # Compare conclusion formula structure
    compare_conclusion_formulas()

    # Test minimal counterfactual
    test_minimal_counterfactual()

    # Capture actual constraints
    print("\n\nCapturing full model checker constraints...")
    print("(This may produce a lot of output)")

    constraints_fin = capture_constraints("finitary", "CF_CM_18")
    constraints_nat = capture_constraints("native", "CF_CM_18")


if __name__ == "__main__":
    main()
